import { useRef } from 'react';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import type { Catalog } from '../types/product';
import { ProductCard } from '../components/ProductCard';
import { MobileHeader } from '../components/MobileHeader';
import { initialFilters, useFilters } from '../hooks/useFilters';
import { useReviews } from '../hooks/useReviews';
import { useMobile } from '../hooks/useMobile';
import { statusLabels } from '../types/review';
export function CatalogPage({catalog}:{catalog:Catalog}) {
 const {reviews,ready}=useReviews();const {filters,setFilters,filtered}=useFilters(catalog.products,reviews,ready);const mobile=useMobile();const dialog=useRef<HTMLDialogElement>(null);
 const choices=(field:'brand'|'category'|'color')=>[...new Set(catalog.products.flatMap(p=>field==='color'?p.colors.map(c=>c.name):[field==='brand'?p.brand:(p.category||p.suggestedCategory)]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 const ordering=<label>Ordenar <select aria-label="Ordenar" value={filters.order} onChange={e=>setFilters({...filters,order:e.target.value})}>{[['name_asc','Nome A–Z'],['name_desc','Nome Z–A'],['reference','Referência'],['price_asc','Preço crescente'],['price_desc','Preço decrescente'],['stock_desc','Maior estoque'],['stock_asc','Menor estoque']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>;
 const controls=<div className="filters"><SlidersHorizontal size={17}/>{(['brand','category','color'] as const).map((field,i)=><label key={field}><span className="sr-only">{['Marca','Categoria','Cor'][i]}</span><select aria-label={['Marca','Categoria','Cor'][i]} value={filters[field]} onChange={e=>setFilters({...filters,[field]:e.target.value})}><option value="">{['Todas as marcas','Todas as categorias','Todas as cores'][i]}</option>{choices(field).map(v=><option key={v}>{v}</option>)}</select></label>)}<select aria-label="Status da revisão" value={filters.status} disabled={!ready} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Alertas" value={filters.warnings} onChange={e=>setFilters({...filters,warnings:e.target.value})}><option value="">Todos os alertas</option><option value="yes">Com alerta</option><option value="no">Sem alerta</option></select><select aria-label="Imagens" value={filters.images} onChange={e=>setFilters({...filters,images:e.target.value})}><option value="">Todas as imagens</option><option value="yes">Com imagem</option><option value="no">Sem imagem</option></select>{mobile&&ordering}<button onClick={()=>setFilters(initialFilters)}>Limpar filtros</button></div>;
 return <div className="catalog-page">{mobile&&<MobileHeader onFilters={()=>dialog.current?.showModal()}/>}
 {!mobile&&<><div className="page-heading"><div><h1>Catálogo para Conferência</h1><p>Revise os produtos antes da publicação.</p></div></div></>}
 <section className="catalog-tools" aria-label="Busca e filtros"><label className="search"><Search size={19}/><input aria-label="Buscar produtos" placeholder={mobile?'Buscar por nome, referência, marca...':'Buscar por nome, referência ou marca...'} value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})}/></label></section>
 {mobile?<><div className="quick-filters" aria-label="Filtros rápidos">{[['Todos','',''],['Molekinha','Molekinha',''],['Molekinho','Molekinho',''],['Menina','','girl'],['Menino','','boy']].map(([label,brand,gender])=><button type="button" key={label} aria-pressed={filters.brand===brand&&filters.gender===gender} onClick={()=>setFilters({...filters,brand,gender})}>{label}</button>)}</div></>:<><div className="desktop-quick-filters" aria-label="Filtros rápidos">{[['Todos','',''],['Molekinha','Molekinha',''],['Molekinho','Molekinho',''],['Revisados','','approved'],['Não revisados','','pending']].map(([label,brand,status])=><button key={label} type="button" disabled={!!status&&!ready} aria-pressed={filters.brand===brand&&filters.status===status&&!filters.gender} onClick={()=>setFilters({...filters,brand,status,gender:''})}>{status&&<i className={`filter-dot ${status}`}/>} {label}</button>)}</div><div className="results-bar"><span>{filtered.length} produtos encontrados</span><div className="desktop-result-tools"><button aria-label="Abrir filtros" onClick={()=>dialog.current?.showModal()}><SlidersHorizontal size={14}/> Filtros</button>{ordering}</div></div></> }<dialog ref={dialog} className="mobile-menu filter-dialog"><div className="section-title"><h2>Filtros e ordenação</h2><button className="mobile-icon-button" aria-label="Fechar filtros" onClick={()=>dialog.current?.close()}><X size={22}/></button></div>{controls}<p>{filtered.length} de {catalog.products.length} modelos</p><button className="primary" onClick={()=>dialog.current?.close()}>Ver produtos</button></dialog>
 {filtered.length?<div className="product-grid">{filtered.map(p=><ProductCard key={p.parentSku} product={p}/>)}</div>:<div className="empty"><Search size={32}/><h2>Nenhum produto encontrado</h2><p>Altere a busca ou limpe os filtros.</p><button onClick={()=>setFilters(initialFilters)}>Limpar filtros</button></div>}</div>;
}
