import { displayImageUrls } from '../utils/productImages';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Download } from 'lucide-react';
import type { Catalog } from '../types/product';
import { useReviews } from '../hooks/useReviews';
import { StatsCards } from '../components/StatsCards';
import { ProductImage } from '../components/ProductGallery';
import { exportRows, toCSV, download } from '../utils/csvExport';
import { date } from '../utils/formatters';
export function ReviewDashboardPage({catalog}:{catalog:Catalog}) {
 const {reviews,user,ready,loading,refresh}=useReviews();const [message,setMessage]=useState('');const [exporting,setExporting]=useState(false);const reviewed=catalog.products.filter(p=>['approved','needs_correction'].includes(reviews[p.reference]?.status)).length;const corrections=catalog.products.filter(p=>reviews[p.reference]?.status==='needs_correction');
 async function exportData(format:'csv'|'json'){setMessage('');setExporting(true);try{const latest=await refresh();const rows=exportRows(catalog.products,latest);download(format==='csv'?toCSV(rows):JSON.stringify({exportedAt:new Date().toISOString(),sourceHash:catalog.sourceHash,products:rows,reviews:latest},null,2),`conferencia-${new Date().toISOString().slice(0,10)}.${format}`,format==='csv'?'text/csv;charset=utf-8':'application/json');setMessage('Exportação concluída com as revisões atualizadas.');}catch{setMessage('Não foi possível buscar as revisões mais recentes. A exportação foi cancelada.');}finally{setExporting(false);}}
 return <><div className="page-heading"><div><h1>Dashboard de conferência</h1><p>Acompanhe a revisão de cada modelo e os ajustes solicitados.</p></div><div className="actions"><button disabled={!user||!ready||exporting||loading} onClick={()=>void exportData('csv')}><Download size={16}/> Exportar conferência CSV</button><button disabled={!user||!ready||exporting||loading} onClick={()=>void exportData('json')}>Exportar JSON</button></div></div><StatsCards catalog={catalog}/>{!ready?<div className="panel"><p>{loading?'Preparando conferência…':'Revisões indisponíveis. Os indicadores não representam o estado atual.'}</p><button disabled={loading} onClick={()=>void refresh().catch(()=>{})}>Atualizar revisões</button></div>:<><section className="panel"><div className="section-title"><h2>Progresso da conferência</h2><strong>{(100*reviewed/catalog.products.length||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</strong></div><progress value={reviewed} max={catalog.products.length||1}/><p>{reviewed} de {catalog.products.length} produtos revisados</p><button disabled={loading} onClick={()=>void refresh().catch(()=>{})}>Atualizar revisões</button></section><section className="panel"><h2>Correções solicitadas · {corrections.length}</h2>{corrections.length?corrections.map(p=><Link key={p.parentSku} className="correction-row" to={`/produto/${p.reference}`}><div className="small-image"><ProductImage url={displayImageUrls(p)[0]} name={p.name}/></div><div><strong>{p.name}</strong><p>Ref. {p.reference}</p><p className="preserve">{reviews[p.reference]?.comment}</p><span className="muted">{reviews[p.reference]?.reviewer_name} · {date(reviews[p.reference]?.reviewed_at)}</span></div></Link>):<p>Nenhuma correção solicitada.</p>}</section><section className="panel"><h2>Continuar conferência</h2>{catalog.products.filter(p=>(reviews[p.reference]?.status??'pending')==='pending').map(p=><Link className="pending-row" key={p.parentSku} to={`/produto/${p.reference}`}>{p.name}<span>Conferir</span></Link>)}</section></>}{message&&<p role="status">{message}</p>}</>;
}
